Kubernetes Controllers
otus-kuber-2020-04/dmitriye_platform pull request #3
Opened 2020-05-11 08:19 UTC by dmitriye

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [x] Задание со *
 - [x] Задание со **

## В процессе сделано:
 - Развернут кластер (master х3, worker х3) при помощи kind.
 - Написаны манифесты для ReplicaSet & Deployment сервисов frontend & paymentservice приложения HipsterShop.
 - Обновление ReplicaSet не повлекло обновления Pod'ов, так как основной задачей ReplicaSet является отслеживание кол-ва готовых подов, чтобы оно соответствовало желаемому кол-ву, а в нашей ситуации необходимое кол-во подов уже было развернуто.
 - Созданы Deployment для стратегий развертывания Blue-Green (maxSurge=100% maxUnavailable=0%) и RollingUpdate (maxSurge=1 maxUnavailable=1).
 - Создан манифест для развертывания DaemonSet на worker нодах.
 - Доработан мнифест DaemonSet для работы на master нодах.
1. Создание кластера
```bash
kind create cluster --config kind-config.yaml
```
2. Применяем манифест `kubernetes-controllers/frontend-replicaset.yaml`
3. Проверяем где развернулись поды
```bash
$ kubectl get pods -o wide
NAME                  READY   STATUS    RESTARTS   AGE     IP           NODE                  NOMINATED NODE   READINESS GATES
node-exporter-7s5zm   1/1     Running   0          26s     10.244.4.3   kind-worker2          <none>           <none>
node-exporter-g7zh8   1/1     Running   0          6s      10.244.5.3   kind-worker           <none>           <none>
node-exporter-hxsmq   1/1     Running   0          16s     10.244.3.3   kind-worker3          <none>           <none>
```
4. Для того, чтобы поды могли также разворачиваться и на master нодах в манифесте необходимо прописать toleration.
```yaml
...
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
...
```
5. Применяем манифест и проверяем где развернулись наши поды
```bash
$ kubectl get pods -o wide
NAME                  READY   STATUS    RESTARTS   AGE     IP           NODE                  NOMINATED NODE   READINESS GATES
node-exporter-7s5zm   1/1     Running   0          26s     10.244.4.3   kind-worker2          <none>           <none>
node-exporter-7t2zg   1/1     Running   0          2m14s   10.244.1.2   kind-control-plane2   <none>           <none>
node-exporter-bnpl9   1/1     Running   0          2m14s   10.244.0.5   kind-control-plane    <none>           <none>
node-exporter-g7zh8   1/1     Running   0          6s      10.244.5.3   kind-worker           <none>           <none>
node-exporter-hxsmq   1/1     Running   0          16s     10.244.3.3   kind-worker3          <none>           <none>
node-exporter-qjjq2   1/1     Running   0          2m15s   10.244.2.2   kind-control-plane3   <none>           <none>
```

## PR checklist:
 - [x] Выставлен label с темой домашнего задания

2020-05-11 08:39 UTC, Jasstkn requested changes
Добрый день! Домашнее задание выполнено верно! Здорово, что уделяете время заданиям со звездочками - они самые важные для хорошего усвоения материала =) И спасибо за подробный ридми - полезно не только для нас, но и для вас. По node-exporter оставила вам комментарий для дальнейших разбирательств, если что пишите в чат в слаке по вопросам.Жду ваших исправлений по заданию с node exporter!

2020-05-11 08:39 UTC, Jasstkn commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +          effect: NoSchedule
Вы начали копать в нужную сторону, но не совсем верно определили tolerations.
Предлагаю вам подробнее ознакомиться с документацией:
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#concepts -> секция Note и с официальным манифестом для node exporter.

2020-05-13 12:52 UTC, Jasstkn commented
@dmitriye увидела, что вернули обратно в очередь на проверку, но изменений, на которые я указала, не было внесено. Вы не согласны с моим ревью?

2020-05-13 14:55 UTC, dmitriye commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +          effect: NoSchedule
```suggestion
        - operator: "Exists"
```

@Jasstkn, спасибо, кажется догадался. В таком варианте получается, что exporter развернется на всех нодах кластера? вне зависимости мастер/воркер ([#mark-the-node-as-control-plane](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#mark-the-node-as-control-plane))

2020-05-13 14:56 UTC, dmitriye commented
@Jasstkn я создал review и не закоммитил его ¯\_(ツ)_/¯

2020-05-13 15:02 UTC, Jasstkn commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +          effect: NoSchedule
@dmitriye да, все верно. Таким образом вы будете запускать нод экспортер на всех нодах в кластере - может быть полезно, чтобы каждый раз не указывать специфичные толерейшнс.

2020-05-13 15:02 UTC, Jasstkn approved these changes

2020-05-13 15:02 UTC, merged